id: QmXgi48oCAdqmjhqf78nmYgyjjcSodbFKjZ5Hok6xLE5Tv
description: ollama plugin - pull
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ollama/pull
domains:
    - GeneratedDomain
execution:
    timeout: 3600s
    memory: 10MB
    call: pull
